platform: linux

image_resource:
  type: docker-image
  source:
    repository: google/cloud-sdk
    tag: alpine

run:
  path: sh
  args:
    - -exec
    - |
      echo "REPORTING_MATOMO_BASE_URL: ${REPORTING_MATOMO_BASE_URL}"
      echo "REPORTING_MATOMO_SITE_ID: ${REPORTING_MATOMO_SITE_ID}"
      echo "REPORTING_BUCKET_NAME: ${REPORTING_BUCKET_NAME}"

      if [ -z "${REPORTING_MATOMO_AUTH_TOKEN+x}" ]; then
        echo "Missing REPORTING_MATOMO_AUTH_TOKEN"
        exit -1
      fi

      echo "REPORTING_MATOMO_AUTH_TOKEN: (set)"

      set -e
      node src/review-report-generator.js

      set +x
      echo $AUTH_KEY > encrypted_key.txt
      set -x

      base64 -d encrypted_key.txt > service-account.json
      gcloud auth activate-service-account --key-file service-account.json
      gcloud config set project $PROJECT

      echo "Copying reports to $REPORTING_GCP_BUCKET_ID"
      gsutil cp "src/out/*.csv" "gs://$REPORTING_BUCKET_NAME/$REPORTING_MATOMO_SITE_NAME/"

inputs:
  - name: census-worth-self-help

caches:
  - path: .npm
