platform: linux

image_resource:
  type: docker-image
  source:
    repository: google/cloud-sdk
    tag: alpine

run:
  path: sh
  args:
    - -exec
    - |

      apk add --no-progress --update nodejs nodejs-npm
      echo "npm version"
      npm -v
      node --version

      export ROOT_FOLDER=$(pwd)
      npm config set cache ${ROOT_FOLDER}/.npm --global

      cd census-worth-self-help/analytics
      npm ci

outputs:
  - name: node-workspace

caches:
  - path: .npm
