resources:
  - name: census-worth-self-help
    type: git
    source:
      uri: https://github.com/ONSdigital/census-worth-self-help.git
      branch: feature/ONS-754-refactor
  
  - name: middle-of-the-night
    type: time
    source:
      start: 2:00 AM
      stop: 3:00 AM
      location: Europe/London

jobs:
  - name: report
    build_log_retention:
      days: 7
      builds: 10
    max_in_flight: 1
    plan:
      - get: middle-of-the-night
        trigger: true

      - get: census-worth-self-help
        trigger: false
      
      - task: generate-report-one
        file: census-worth-self-help/pipeline/tasks/generate-analytics-report.yml
        params:
          AUTH_KEY: ((gcp.service-account-key))
          PROJECT: ((gcp.project-name))
          REPORTING_MATOMO_BASE_URL: ((analytics.matomo-query-prefix))
          REPORTING_MATOMO_AUTH_TOKEN: ((analytics.matomo-auth-token))
          REPORTING_MATOMO_SITE_ID: 12
          REPORTING_BUCKET_NAME: ((analytics.analytics-reports-bucket))

      - task: generate-report-two
        file: census-worth-self-help/pipeline/tasks/generate-analytics-report.yml
        params:
          AUTH_KEY: ((gcp.service-account-key))
          PROJECT: ((gcp.project-name))
          REPORTING_MATOMO_BASE_URL: ((analytics.matomo-query-prefix))
          REPORTING_MATOMO_AUTH_TOKEN: ((analytics.matomo-auth-token))
          REPORTING_MATOMO_SITE_ID: 2
          REPORTING_BUCKET_NAME: ((analytics.analytics-reports-bucket))
            
        

