runtime: nodejs10
service: default
default_expiration: 60m
handlers:
  - url: /admin/(.*\.yml)
    script: auto
    secure: always

  - url: /admin/cms.css
    script: auto
    secure: always

  - url: /admin/
    expiration: 5m
    script: auto
    http_headers:
      Content-Security-Policy: |-
        connect-src 'self' blob: https://api.github.com https://upload.uploadcare.com; default-src 'self'; img-src 'self' data: blob: https://*.githubusercontent.com https://ucarecdn.com https://*.amazonaws.com; media-src https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';

  - url: /admin/index.html
    script: auto
    http_headers:
      Content-Security-Policy: |-
        connect-src 'self' blob: https://api.github.com https://upload.uploadcare.com; default-src 'self'; img-src 'self' data: blob: https://*.githubusercontent.com https://ucarecdn.com https://*.amazonaws.com; media-src https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';

  - url: /admin/cms.js
    expiration: 30m
    script: auto
    secure: always

  - url: /sw.js
    script: auto
    secure: always

  - url: /(.*\.js)
    script: auto
    secure: always

# Protected content managed images and fonts (driven by CMS)
  - url: /assets/(.*\.(gif|ico|jpeg|jpg|png|svg))
    script: auto
    secure: always  

# Online route for offline detection
  - url: /online
    expiration: 1d
    mime_type: text/plain
    static_files: public/online.txt
    secure: always
    upload: public/online.txt

# Robots.txt
  - url: /robots.txt
    expiration: 1d
    script: auto
    secure: always

# No need for protection for images and fonts driven from code repository
  - url: /(.*\.(gif|ico|jpeg|jpg|png|svg))
    expiration: 1d
    script: auto
    secure: always

# Fonts
  - url: /(.*\.(woff|woff2|ttf|eot))
    expiration: 7d
    script: auto
    secure: always

  - url: /icons
    expiration: 1d
    script: auto
    secure: always

# Protected page handling
  - url: /(.*)
    script: auto
    secure: always
